-- Nexa Digital — Supabase PostgreSQL Schema & Initial Data

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'admin',
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  name_ar TEXT NOT NULL,
  name_en TEXT NOT NULL,
  desc_ar TEXT NOT NULL,
  desc_en TEXT NOT NULL,
  features_ar TEXT NOT NULL DEFAULT '[]',
  features_en TEXT NOT NULL DEFAULT '[]',
  category TEXT NOT NULL DEFAULT 'development',
  icon TEXT NOT NULL DEFAULT 'Sparkles',
  image TEXT,
  price TEXT,
  duration TEXT,
  status TEXT NOT NULL DEFAULT 'published',
  display_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title_ar TEXT NOT NULL,
  title_en TEXT NOT NULL,
  type_ar TEXT,
  type_en TEXT,
  desc_ar TEXT,
  desc_en TEXT,
  cover_image TEXT,
  gallery TEXT DEFAULT '[]',
  project_url TEXT,
  service_id BIGINT REFERENCES services(id) ON DELETE SET NULL,
  is_demo INTEGER NOT NULL DEFAULT 1,
  status TEXT NOT NULL DEFAULT 'published',
  display_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS faqs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_ar TEXT NOT NULL,
  question_en TEXT NOT NULL,
  answer_ar TEXT NOT NULL,
  answer_en TEXT NOT NULL,
  service_id BIGINT REFERENCES services(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'published',
  display_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quote_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  company TEXT,
  service_type TEXT,
  description TEXT NOT NULL,
  budget TEXT,
  deadline TEXT,
  preferred_contact TEXT DEFAULT 'email',
  file_path TEXT,
  status TEXT NOT NULL DEFAULT 'new',
  internal_notes TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contact_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT,
  message TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'new',
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_name TEXT NOT NULL,
  role_ar TEXT,
  role_en TEXT,
  quote_ar TEXT NOT NULL,
  quote_en TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'published',
  display_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin_notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_request_id BIGINT REFERENCES quote_requests(id) ON DELETE CASCADE,
  note TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS site_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Seed initial admin user: admin@nexadigital.com / ChangeMe123!
INSERT INTO users (email, password_hash, name, role)
VALUES ('admin@nexadigital.com', '$2a$10$9Gv.k67sT/t5Z8fR7E2hNeGgDq2Uu/bW1.rS8j6V4U9x0L1M2N3O4', 'Admin')
ON CONFLICT (email) DO NOTHING;

-- Seed default settings
INSERT INTO site_settings (key, value) VALUES
  ('site_name', 'Nexa Digital'),
  ('tagline_ar', 'نحوّل أفكارك إلى تجارب رقمية ناجحة'),
  ('tagline_en', 'We turn your ideas into successful digital experiences'),
  ('email', 'dnexa99@gmail.com'),
  ('phone', '+213795329388'),
  ('whatsapp', '+213795329388'),
  ('whatsapp_enabled', 'true'),
  ('address_ar', 'الجزائر'),
  ('address_en', 'Algeria'),
  ('instagram', 'https://www.instagram.com/nexa_dig?stkn=bzJncW9zaDUxMHQ1'),
  ('content_service_enabled', 'false'),
  ('default_locale', 'ar'),
  ('dark_mode_enabled', 'false')
ON CONFLICT (key) DO NOTHING;
